### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by perfecto25** [thilux/ssh_metro_server#5]
mrx@mrxDEV1 ~/d/m/m/plugins (master ⚡↩) sudo pip install ssh-metro-server
Collecting ssh-metro-server
  Downloading ssh_metro_server-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7SC0UF/ssh-metro-server/setup.py", line 82, in <module>
        'testing': requires,
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
        return self.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2418, in resolve
        raise ImportError(str(exc))
    ImportError: 'module' object has no attribute 'check_specifier'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7SC0UF/ssh-metro-server/
You are using pip version 8.1.2, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by thilux** [comment]
Hi @perfecto25,

This appears to be an issue with your version of setup tools as described here in this other bug: https://github.com/pypa/pip/issues/4104

Please update setuptools and get back to me on whether that works or not.

If that doesn't work, try updating pip as suggested by pip itself on the excerpt you provided:

```
pip install --upgrade pip
```

If still that doesn't work, please let me know what is your operating system and which version and I will try to simulate the issue to go back and try to fix it.

Thank you!
